#+AUTHOR: Mehran Pesteie
#+EMAIL: mehranp at ece (dot) ubc (dot) ca
#+OPTIONS: toc:nil

* Docker image of the US spine classification system (Python implementation).
** Methods
- Multi-scale and multi-directional feature extraction using LDH
- Pattern classification via MLP
** Data
- Sagittal planes of 3D US volumes collected with motorized transducer from 13 volunteers
** Result summary:
- 97% and 94% accuracy on train and test data, respectively. For more details, please refer to the [[http://link.springer.com/article/10.1007/s11548-015-1202-5][paper]].
** Dependencies:
- docker
- numpy
- opencv
- No GPU!
** Build:

#+BEGIN_SRC bash
sh build.sh
#+END_SRC

** Run:
#+BEGIN_SRC 
sh run.sh [path to the data folder] [data file]
#+END_SRC

ex: sh run.sh /home/deepinfer/image_data img1.jpg
** Citation:
If you use this code and docker image, please cite:
- Pesteie, M., Abolmaesumi, P., Ashab, H. A. D., Lessoway, V. A., Massey, S., Gunka, V., & Rohling, R. N. (2015). Real-time ultrasound image classification for spine anesthesia using local directional Hadamard features. International journal of computer assisted radiology and surgery, 10(6), 901-912.
- Mehrtash, A., Pesteie, M., Hetherington, J., Behringer, P. A., Kapur, T., Wells, W. M., ... & Abolmaesumi, P. (2017, March). DeepInfer: open-source deep learning deployment toolkit for image-guided therapy. In SPIE Medical Imaging (pp. 101351K-101351K). International Society for Optics and Photonics.
